### ISSUE TITLE
Saving 24 bit PNGs

### ISSUE THREAD

**Issue by Starbuck5** [libsdl-org/SDL_image#282]
Hello,

I was using the PNG saving functionality and I noticed that my 24 bit surfaces weren't saving as 24 bit PNGs.

Looking at the source: https://github.com/libsdl-org/SDL_image/blob/main/IMG_png.c#L631-L633, I see that this is because my Surface was BGR24. If the surface being saved isn't **exactly** RGB24, it will fall through and be converted to be saved as 32 bit.

This is not a big problem for me or anything, I was just curious to look through the code.

Here's a suggested patch (untested):
```c
        else if (surface->format->format == SDL_PIXELFORMAT_RGB24) {
            png_color_type = PNG_COLOR_TYPE_RGB;
        }
        else if (!SDL_ISPIXELFORMAT_ALPHA(surface->format->format)) {
            png_color_type = PNG_COLOR_TYPE_RGB;
            source = SDL_ConvertSurfaceFormat(surface, SDL_PIXELFORMAT_RGB24, 0);
        }
        else if (surface->format->format != png_format) {
            source = SDL_ConvertSurfaceFormat(surface, png_format, 0);
        }
```

One other thing I was confused about was pixelformat endianness. The `png_format` variable is used to guard endianness for the 32 bit ones, but the 24 bit once uses PIXELFORMAT_RGB24 unguarded. I suppose RGB24 is an alias for the right thing on each endianness. Then should SDL_Image use the (new in SDL 2.0.5) aliases for RGB32 as well?

**Comment by slouken** [comment]
Feel free to submit a tested patch. The PNG files are compressed and most applications are optimized to handle 32-bit surfaces rather than 24-bit surfaces, so the default is probably fine, but I'm not opposed to changing it either.

SDL_image can be updated to use the RGB32 aliases, just nobody's gone through and updated all the image loaders yet. Feel free to submit a PR for that as well, if you'd like to tackle it.
