### ISSUE TITLE
Why is WIC backend disabled by default?

### ISSUE THREAD

**Issue by v1993** [libsdl-org/SDL_image#358]
Is this to support old Windows versions? Because it's not tested well enough? Or is there some other reason?

**Comment by madebr** [comment]
I ported this from autotools, where it was always disabled.
https://github.com/libsdl-org/SDL_image/blob/c1b7cf959c7d3150b0707f95a0c5268689c9e537/configure.ac#L290
[This discussion from 2 years ago](https://github.com/libsdl-org/SDL_image/pull/203#discussion_r769711376) point at lack of trust in the wic backend.

I think the actual reason is that the current implementation does not allow to make use of libjpeg and wic simultaneously.
See
https://github.com/libsdl-org/SDL_image/blob/c37c316cce394eb11f0396b2feed9785525c76af/CMakeLists.txt#L403

By refactoring the code to being able to dynamically choose a backend, I think wic can be enabled.
Would SDL hints be a good for this?

**Comment by v1993** [comment]
> I think the actual reason is that the current implementation does not allow to make use of libjpeg and wic simultaneously.

And yet Image I/O is enabled by default, go figure. I guess that's for historical reasons? Looking back, it seems that WIC backend came from a user patch while Image I/O was contributed much earlier by one of core devs. But I may be wrong on this one.
> [This discussion from 2 years ago](https://github.com/libsdl-org/SDL_image/pull/203#discussion_r769711376) point at lack of trust in the wic backend.

Quoting linked discussion:

> And actually I'm not fond of enabling this one - it's not enabled in autotools, it's not enabled in MSVC project files - and who knows why..

Which gives us circular reasoning - it's off by default because there's no trust in it due to being off by default...

> By refactoring the code to being able to dynamically choose a backend, I think wic can be enabled.
> Would SDL hints be good for this?

Why not, SDL hints sound like a fine tool for this job. Make format initialization fill in function pointers for preferred decoder and then use those.

My main motivation for asking this is https://github.com/mesonbuild/wrapdb/pull/982. If lack of ability to switch at runtime to libpng/libjpeg/stb_image is the main concern, do you think defaulting to WIC on library-user-controlled builds would make sense?

**Comment by slouken** [comment]
It's off by default because it gave different color values for decoded images. We wanted decoded output to be consistent across platforms.
