### ISSUE TITLE
x64 DLL size difference

### ISSUE THREAD

**Issue by dstarosta** [libsdl-org/SDL_image#489]
Version 2.8.2 DLL was around 170 KB while version 2.8.3 DLL is 262 KB. The difference in x86 DLLs is about 7 KB. Is that a build issue?

**Comment by slouken** [comment]
Does the main build have the same problem?

**Comment by madebr** [comment]
SDL3 does not have it, SDL3_image has it.
I think it's because the VisualC project of SDL3 uses `/MT` (static runtime) whereas SDL3_image uses `/MD` (shared runtime).

**Comment by madebr** [comment]
Building a x64 SDL3_image.dll with `/MD` creates a 190KB dll, using `/MT` increases it to 280KB.

**Comment by slouken** [comment]
Minimizing C runtime dependencies is worth 90KB, and anyone who wants to can rebuild it themselves with different options.

**Comment by madebr** [comment]
SDL_image now uses static runtime since https://github.com/libsdl-org/SDL_image/commit/e832856db602fe18c5ada71b608f77cb74cd4218

It's not what OP hoped for (file size of SDL2_image.dll increased even more), but we can now account for the file size differences.
SDL2_image.dll of the mingw package has not changed though :)

**Comment by madebr** [comment]
I'll fix the other satellite libraries along with my release script changes.
